trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

resources:
  repositories:
    - repository: nls-pipeline-templates
      type: git
      name: NLS/nls-pipeline-templates
      ref: main

extends:
  template: azure-pipelines-java.yml@nls-pipeline-templates
  parameters:
    isVersionedProject: true
    jdkVersion: 1.21
    mavenReleaseGoal: deploy
    sonarOptionalCoverageExclusions: '**/config/**'
    sonarOptionalExclusions: '**/graphhopper/isochrone/ShortestPathTree.java,**/graphhopper/routing/PathRouter.java'
    pushToGitHub: true
