trigger:
  batch: true
  branches:
    include:
      - master
      - feature/*

pool:
  vmImage: 'ubuntu-latest'

steps:

  - task: Maven@3
    displayName: Maven build
    inputs:
      publishJUnitResults: false
      sonarQubeRunAnalysis: false
      jdkVersionOption: 1.11
      ${{ if eq( variables['Build.SourceBranch'], 'refs/heads/master') }}:
        mavenAuthenticateFeed: true
        goals: 'deploy'
      ${{ if ne( variables['Build.SourceBranch'], 'refs/heads/master') }}:
        goals: 'clean verify'
