pool:
  vmImage: ubuntu-latest

resources:
  repositories:
    - repository: nls-pipeline-templates
      type: git
      name: NLS/nls-pipeline-templates
      ref: feature/70576-use-nls-github-user

extends:
  template: azure-pipelines-java.yml@nls-pipeline-templates
  parameters:
    isVersionedProject: true
    mavenReleaseGoal: deploy
    sonarOptionalCoverageExclusions: '**/config/**'
    sonarOptionalExclusions: '**/graphhopper/isochrone/ShortestPathTree.java,**/graphhopper/routing/PathRouter.java'
    pushToGitHub: true

