trigger:
  batch: true
  branches:
    include:
      - master
      - feature/*

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.11'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      ${{ if eq( variables['Build.SourceBranch'], 'refs/heads/master') }}:
        mavenAuthenticateFeed: true
        goals: 'deploy'
      ${{ if ne( variables['Build.SourceBranch'], 'refs/heads/master') }}:
        goals: 'verify'
